sonar.organization=lopera2806
sonar.projectKey=Lopera2806_Proyecto_4
sonar.projectName=Proyecto_4
sonar.sources=.
sonar.java.binaries=.
sonar.token=78db086e6c6716a3ee38be8d20ecd49c2d1f299e
sonar.scanner.skipJreProvisioning=true